environment:
  matrix:
    - job_name: win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python38-x64
    - job_name: macos64
      APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVCVYiWsKFfQn2/PqmWCH0fzwgpm4A71YlAwuTL3Rl0HHTUcXVRpgHUxEEm+eMNZbf1Sh1b840+3SkDaMmfFtbxQ6Qo+64EyZeiemYmJ3T00qMAjX++zJVEnQI8dqKDykq2cc5cLJqqRaUCiuy9uxfO5cihW/xwswdzyz4pv/xO7RlpQVcghn56DEkP2GRsrAwq71OGataJ4WK1W+/Kk19sWAZs8aQemPGMXAQp5f6PwfvCFXJDSXhkc6a7F7sE3r+nAdoXeTzhtgspeRvnnbWH48/iagEyGBmbao75/QICWXKIB+VUox2Cz65VwCcslC/PM6sEGdZgHvElKB1teLf showard@esc-303123

init:
- cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
- sh: brew install tcl-tk pyenv pyenv-virtualenv
- sh: eval "$(pyenv init -)"
- sh: SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/ PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' --enable-framework" pyenv install 3.7.8
- sh: pyenv global 3.7.8
- sh: pyenv virtualenv 3.7.8 pcsienv
- sh: pyenv activate pcsienv
- python --version
- python -m pip install opencv-python numpy imageio bitstring pylbfgs pyserial pillow pyinstaller
- sh: pyenv rehash

build_script:
- pyinstaller pcsiGUI-linuxOD.spec

#on_finish:
#- sh: export APPVEYOR_SSH_BLOCK=true
#- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

artifacts:
- path: dist\pcsiGUI
  name: pcsiGUI-$(job_name)

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: 4PhCdC/CzF+nHR8T/hiD2kw0480iD4ap4rf4pN5+eXvF3Mfn0EvQFZookOv1xO/5
  repository: maqifrnswa/pcsi
  artifact: pcsiGUI-$(job_name)
  on:
    APPVEYOR_REPO_TAG: true
