environment:
  PY_VER: 3.8
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\\Python$(PY_VER)38-x64
      OSNAME: win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      OSNAME: linux64
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      OSNAME: macos64

stack: python $(PY_VER)

init:
- cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
- sh: echo "testing"
- sh: sudo apt-get install python$(PY_VER)-dev
- python --version
- python -m pip install opencv-python numpy imageio bitstring pylbfgs pyserial pillow pyinstaller

build_script:
- pyinstaller pcsiGUI-linuxOD.spec

artifacts:
- path: dist\pcsiGUI
  name: pcsiGUI-$(OSNAME)

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: 4PhCdC/CzF+nHR8T/hiD2kw0480iD4ap4rf4pN5+eXvF3Mfn0EvQFZookOv1xO/5
  repository: maqifrnswa/pcsi
  artifact: pcsiGUI-$(OSNAME)
  on:
    APPVEYOR_REPO_TAG: true
